### ISSUE TITLE
Did the API path change since 2 Nov?

### ISSUE THREAD

**Issue by andreacoppini** [danimart1991/pvpc-hourly-pricing-card#44]
As of 2 Nov, PVPC card and the built in PVPC integration in HA has stopped working.

Log just says:
Logger: homeassistant.components.pvpc_hourly_pricing.sensor
Source: components/pvpc_hourly_pricing/sensor.py:136
Integration: Spain electricity hourly pricing (PVPC) (documentation, issues)
First occurred: 22:58:51 (5 occurrences)
Last logged: 23:05:04

sensor.pvpc: repeated bad data update, mark component as unavailable source

**Comment by desegura** [comment]
That's right, can @danimart1991 check this issue?

**Comment by danimart1991** [comment]
I close already 4 issues about this. I left this one open so all can see that the problem is not related with the card.

This repository is only for the development of the PVPC custom card. The PVPC integration is native from Home Assistant and all the related issues must be in the [Home Assistant repository](https://github.com/home-assistant/core/issues).

Indeed, there is already [an Issue](https://github.com/azogue/aiopvpc/issues/27) in the component used by HA for the integration.

Related Issues:
- https://github.com/danimart1991/pvpc-hourly-pricing-card/issues/41
- https://github.com/danimart1991/pvpc-hourly-pricing-card/issues/42
- https://github.com/danimart1991/pvpc-hourly-pricing-card/issues/43

**Comment by azogue** [comment]
What a day, @danimart1991 🙈🍻

**Comment by camochu** [comment]
Working again with HA Core 2021.11.1 !!!
Thanks @azogue and @danimart1991
