### ISSUE TITLE
Graph not shown since 2023.7.0b0

### ISSUE THREAD

**Issue by katiuskt** [danimart1991/pvpc-hourly-pricing-card#61]
The graph view in the PVPC Hourly Pricing Card is not working since 2023.7.0b0 release:

![imagen](https://github.com/danimart1991/pvpc-hourly-pricing-card/assets/75622100/f75892d7-8ca2-4ce5-a0a0-4b4e4d44f748)

Only the "colored dot" is shown but the graph itself is not visible. Attributes are received OK from PVPC integration  but data is not shown in the graph.

In case it helps, just created a new dashboard with only the PVPC card (with graph enabled) I can see this in browser developer console:
![imagen](https://github.com/danimart1991/pvpc-hourly-pricing-card/assets/75622100/9664d0d5-0b40-476f-9d19-57a20a561dad)

Under "card configuration" with "Show graph" enabled, browser developer console shows this:
![imagen](https://github.com/danimart1991/pvpc-hourly-pricing-card/assets/75622100/ffaa3acd-bc7e-4783-bd68-12c08e10c0bb)

I've seen https://github.com/home-assistant/frontend/pull/16799 in 2023.07 release related with "timezone" but not sure if it might be related/the root cause of this issue

**Comment by katiuskt** [comment]
Nevermind. It seems like the problem was on Home Assistant side: until b6 graph still wasn't visible but in final 2023.07 version graph is shown again.
Closing

**Comment by danimart1991** [comment]
It's broken to me in the 2023.07 😢

![image](https://github.com/danimart1991/pvpc-hourly-pricing-card/assets/5982912/b3898b56-960d-48d7-83b6-919ec4aa6942)

**Comment by L0bit0** [comment]
Same to me…

**Comment by msanchezt** [comment]
Same here, broken as well.

**Comment by msanchezt** [comment]
Wondering if it could be related with this that was introduced on 2023.7:

_Select the timezone to use/display
You can now select which timezone the Home Assistant interface should use in your user profile. Useful when traveling or when you, for example, manage an instance for a relative in a different time zone._

**Comment by pepeaantonio** [comment]
Lo mismo aqui...
![Captura de pantalla 2023-07-08 113804](https://github.com/danimart1991/pvpc-hourly-pricing-card/assets/72303218/6c3cc624-b731-4147-96b0-11b9d0863d4a)

**Comment by ismaelrivas** [comment]
Same to me.
![Screenshot_20230709-075720~2](https://github.com/danimart1991/pvpc-hourly-pricing-card/assets/49950192/c8d3e59e-098e-46a7-8984-41fbd6dd24e1)

**Comment by davefx** [comment]
My setup was also affected...

**Comment by Agimgrue** [comment]
Same here, can't see graph

**Comment by Albruaje** [comment]
same for me!!

**Comment by andreout** [comment]
Idem problema. Volvim para a 2023.6.3 e funciona

**Comment by thor9898** [comment]
Same for me

**Comment by antoniochacon** [comment]
Same for me. I can´t see the graph.

**Comment by emilianogetino** [comment]
Ami me sucede lo mismo

**Comment by gvulvae** [comment]
Still not working on 2023.7.2

**Comment by zawsar** [comment]
Same here, does it work for anyone? in previous issues I've had to reinstall the addon after the HA upgrade and it worked but not now.

**Comment by danimart1991** [comment]
Gracias a todos por vuestros comentarios, el bug debería estar solucionado en la siguiente actualización de la tarjeta (versión 1.10.0).

Recordad que esta tarjeta se ha desarrollado de manera desinteresada con el tiempo y esfuerzo de sus colaboradores y que agradecemos que se comparta para que pueda llegar a más gente, así como cualquier donación a través de [GitHub Sponsors](https://github.com/sponsors/danimart1991) o [Paypal](https://www.paypal.me/danimart1991) para poder seguir trabajando en ella y poder solucionar los problemas que surjan cuanto antes.

---

Thank you all for your comments, the bug should be fixed in the next update of the card (version 1.10.0).

Remember that this card has been developed selflessly with the time and effort of its collaborators and that we appreciate that it is shared so that it can reach more people, as well as any donation through [GitHub Sponsors](https://github.com/sponsors/danimart1991) or [Paypal](https://www.paypal.me/danimart1991) to be able to continue working on it and to be able to solve any problems that arise as soon as possible.

**Comment by sargue** [comment]
Muchas gracias @danimart1991 .

Por mi parte he aplicado el cambio al fork que incluye la info de excedentes: https://github.com/danimart1991/pvpc-hourly-pricing-card/pull/47

**Comment by Albruaje** [comment]
Gracias! Acompaño de una pequeña donación.


*Albruaje*

**Comment by andreout** [comment]
Mais uma pequena achega. Muitas pequenas fazem uma grande
Saúde
